name: 💡 Pitch
description: Propose a new project
type: "Pitch"
body:
  - type: markdown
    attributes:
      value: |
        There is no idea dumb enough that shouldn't be listened.
        Please fill out the form so we can discuss it.
  - type: textarea
    id: problem
    attributes:
      label: The Problem
      value: |
        _Describe the raw idea or the problem to solve, not the solution. 
        Why is this important? What pain does it solve?_
    validations:
      required: true
  - type: dropdown
    id: appetite
    attributes:
      label: The Appetite
      value: |
        _Define the max amount of time/effort the team should spend to solve it.
        Remember: this is not how much you think it's going to take to implement the best possible
        solution, but how much time you are willing to invest on it._
      options:
        - 1 week
        - 2 weeks
        - 3 weeks
        - 4 weeks
        - 5 weeks
  - type: textarea
    id: solution
    attributes:
      label: The Solution
      value: |
        _Outline the core elements of the solution. How would it work? 
        Describe at a high level with words, sketches, or wireframes. Focus on the 
        “fat marker” version, not fine details._

        _Tip: You can attach images or files by clicking this area to highlight it and 
        then dragging files in._
  - type: textarea
    id: rabbit_holes
    attributes:
      label: The Rabbit Holes
      value: |
        _List potential tricky parts that could consume lots of time or introduce uncertainty. 
        Identify what to avoid going deep into._

        - 
  - type: textarea
    id: no_gos
    attributes:
      label: The No-Gos
      value: |
        _Clearly state what is explicitly excluded from this pitch, to prevent scope creep._

        - 
  - type: textarea
    id: delivery
    attributes:
      label: The Delivery
      value: |
        _We need to know how we will ship this. How much time we need for it? Is it complex? Does it require data
        migrations? Will we do partial rollout?_
  - type: textarea
    id: validations
    attributes:
      label: The Validation
      value: |
        _Describe here how we could validate the solution actually solved the problem.
        This includes the actual observability, not just a quick "how to test" for the stakeholders,
        but which metrics should we keep track of later, after the project is delivered._
  - type: textarea
    id: to_dos
    attributes:
      label: The To-Dos
      value: |
        _A broken-down list of tasks we need to execute to implement the solution.
        Start with an abstract checklist, so later we can convert the checklist item into sub-issues of
        this pitch, open a project for it and plan its execution._

        - [ ] Kickoff the project
        - [ ] 
