name: 🛠️ Task
description: A specific piece of work, often infra, migration, or setup with little to no code involved
type: "Task"
body:
  - type: markdown
    attributes:
      value: |
        A Task is a concrete piece of work that needs to be done, usually without much product discussion.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is the task to be completed?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps / Plan
      description: Break down what needs to be done, if possible.
      value: "- [ ] "
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Are there other tasks/issues this depends on?
      value: "- "
