name: 🐛 Bug Report
description: An unexpected problem or behavior
type: "Bug"
body:
  - type: markdown
    attributes:
      value: |
        Please describe the problem clearly so it can be reproduced and fixed.
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How critical is this issue?
      options:
        - 🔴 Critical (blocks work, crashes, data loss)
        - 🟠 Major (big impact, but workaround exists)
        - 🟡 Minor (annoyance, cosmetic issue)
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      value: _What’s happening that shouldn’t?_
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      value: |
        _What are the exact steps needed to trigger the bug?_

        1. 
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      value: _What actually happens?_
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      value: _What should happen instead?d_
