name: 🛠️ Enhancement
description: Improvements, refactors, DevX changes, or non-critical performance boosts
type: "Enhancement"
body:
  - type: markdown
    attributes:
      value: |
        Suggest improvements that make development smoother or the product better without changing core functionality.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      value: _What’s the improvement you’re suggesting?_
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      value: _Why is this improvement worth doing? What pain does it reduce?_
  - type: textarea
    id: approach
    attributes:
      label: Approach
      value: _How could this be achieved technically?_
  - type: textarea
    id: scope
    attributes:
      label: Scope / Impact
      value: _Does this affect users, developers, performance, or maintainability?_
